sudo: required

language: python
python:
  - "3.6"

jobs:
  include:

    - stage: static analysis
      install: pip install flake8
      script:
      - flake8 --exit-zero .

    - stage: unit tests
      services:
      - docker
      env:
        COMPOSE_VERSION: 1.19.0
      install:
      - pip install codecov
      before_script:
      - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname
        -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      - echo -e "USERNAME=$CREDENTIAL_USERNAME\nPASSWORD=$CREDENTIAL_PASSWORD" >> .env
      - sudo docker-compose -f docker-compose.test.yml build
      - sudo docker-compose -f docker-compose.test.yml run -d db
      script:
      - sudo docker-compose -f docker-compose.test.yml run --rm sut
      after_script:
      - codecov

    - stage: deploy to staging
      install: skip
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_AUTH_TOKEN
        app: cardinalstestbeta
        on:
          repo: amandabezerra/2018.1-Cardinals
          branch: config

    - stage: deploy to production
      install: skip
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_AUTH_TOKEN
        app: cardinalstest
        on:
          repo: amandabezerra/2018.1-Cardinals
          branch: master

