sudo: required
  
language: python

services:
  - docker
  
env:
  COMPOSE_VERSION: 1.19.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 

before_script:
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml up -d

script:
  - docker-compose -p tests run -p 8000 --rm web python manage.py test