sudo: required
language: python
services:
- docker
env:
  COMPOSE_VERSION: 1.19.0
before_install:
- curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
before_script:
- sudo docker-compose -f docker-compose.test.yml build
script:
- sudo docker-compose -f docker-compose.test.yml run --rm sut
deploy:
  provider: heroku
  api_key:
    secure: "JOnWMqTkXrnGJtPvN0K8VFekm4Qms8uapqTXl7UcK+PmZvP7Hd0dQ0JeKeYwPlB8NdZLw/jTunhqlqpALjZN3F/SscZa5wcWBCq9aeUzi2d5ZXllBJGzH5iauZb4RPjmCBFpFcYxApBNxwdX4bJ2MN11KahodHm1uga4KOMjx3oXD5RfMkKgKlPUwt4IxN6Xuiz6+Lf3HcC9USy64A/CTU8g5gAVNtBkie2xqv1BQOuP2E3DLnFd7ygCWtcDomf3srEqkQ2yoMC3FqcWR389taAFhDp8jx2aH7v9g3daroEnmRSDF7imEqZjWMqm48dK142w+Xf7hh11Jl0KEYnmL5INywTggiywbTyXwgZTEvKsnMnJB/CU+lj2DI4L4g2LqNxCOKLLMHkwEzlAchaRea5gwsK6e23HQsPf3nweLy6/tkZFI1B4BlYw8vHNGdyecTsdx3FmRLjKkCloNBiEGBIIzCO0PEDnrr4LtWWmPTolmG8lGn8THQ2NArnwvJJnugZrrXo9A+la+D4EG4HyB1oxuGmTJ06n7n24w1+nHl82+rPTxrr+BAPoK8rnUbWIdH4onlQrZx/QsOiZVeup0CnD0LB8Rrryi7UGbtnYDROWd+o3VJGmtTL/JdACLLA7K3Xis2efwqMjA34o3YRgr6iK9jjkSanpzJ4Tkow0R1U="
  app: cardinals
  on:
    repo: fga-gpp-mds/2018.1-Cardinals
    branch: config_deploy
