version: '3'

services:
  
  db:
    image: postgres
    ports:
      - "5432"
  
  web:
    build: .
    command: ./run.sh
    volumes:
      - .:/code
      - ./run.sh:/run.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
