version: '3'

services:

  sut:
    build: .
    depends_on:
      - db
      - web
    command: ./run_tests.sh

  db:
    image: postgres

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
