site_name: Cardinals
pages:
    - Início:
        - Sobre: index.md
        - Equipe: documentos/equipe.md
        - Guia de contribuição: CONTRIBUTING.md
        - Código de conduta: CODE_OF_CONDUCT.md
        - Instalação: documentos/instalacao.md
    - Desenvolvimento:
        - Documento de Visão: documentos/Documento-de-Visão.md
        - Documento de Arquitetura: documentos/Documento-de-Arquitetura.md
    - Gestão:
        - Termo de Abertura do Projeto: documentos/Termo-de-Abertura-do-Projeto.md
        - Estrutura Analítica do Projeto: documentos/EAP.md
        - Práticas Ágeis: documentos/Práticas-Ágeis-Adotadas.md
        - Monitoramento de issues: documentos/Monitoramento-de-issues-pelo-Zenhub.md
    - Roadmaps:
        - Geral: documentos/roadmap-geral.md
        - Arquitetura: documentos/roadmap-arquitetura.md
    - DevOps:
        - Roadmap: documentos/DevOps/roadmap-devops.md
        - Pipeline: documentos/DevOps/devops-pipeline.md
        - Pipeline explicado: documentos/DevOps/devops-pipeline-explicado.md
    - Sprint 0:
        - Planejamento: documentos/Sprints/00/Planejamento.md
        - Resultados: documentos/Sprints/00/Resultados.md
    - Sprint 1:
        - Planejamento: documentos/Sprints/01/Planejamento.md
        - Resultados: documentos/Sprints/01/Resultados.md
    - Sprint 2:
        - Planejamento: documentos/Sprints/02/Planejamento.md
        - Resultados: documentos/Sprints/02/Resultados.md
    - Sprint 3:
        - Planejamento: documentos/Sprints/03/Planejamento.md
        - Resultados: documentos/Sprints/03/Resultados.md
    - Sprint 4:
        - Planejamento: documentos/Sprints/04/Planejamento.md
        - Resultados: documentos/Sprints/04/Resultados.md
    - Sprint 5:
        - Planejamento: documentos/Sprints/05/Planejamento.md
        - Resultados: documentos/Sprints/05/Resultados.md
    - Sprint 6:
        - Planejamento: documentos/Sprints/06/Planejamento.md
        - Resultados: documentos/Sprints/06/Resultados.md
    - Sprint 7:
        - Planejamento: documentos/Sprints/07/Planejamento.md
        - Resultados: documentos/Sprints/07/Resultados.md
    - Sprint 8:
        - Planejamento: documentos/Sprints/08/Planejamento.md
        - Resultados: documentos/Sprints/08/Resultados.md
    - Sprint 9:
        - Planejamento: documentos/Sprints/09/Planejamento.md
        - Resultados: documentos/Sprints/09/Resultados.md
    - Sprint 10:
        - Planejamento: documentos/Sprints/10/Planejamento.md
        - Resultados: documentos/Sprints/10/Resultados.md
    - Sprint 11:
        - Planejamento: documentos/Sprints/11/Planejamento.md
        - Resultados: documentos/Sprints/11/Resultados.md
    - Sprint 12:
        - Planejamento: documentos/Sprints/12/Planejamento.md
        - Resultados: documentos/Sprints/12/Resultados.md
    - Sprint 13:
        - Planejamento: documentos/Sprints/13/Planejamento.md
        - Resultados: documentos/Sprints/13/Resultados.md
    - Sprint 14:
        - Planejamento: documentos/Sprints/14/Planejamento.md
        - Resultados: documentos/Sprints/14/Resultados.md
    - Sprint 15:
        - Planejamento: documentos/Sprints/15/Planejamento.md


theme:
  name: 'rtd-dropdown'

repo_url: https://github.com/fga-gpp-mds/2018.1-Cardinals
