site_name: Cardinals
pages:
    - Home: index.md
    - Documentação de Desenvolvimento:
        - Documento de Visão: documentos/Documento-de-Visão.md
        - Documento de Arquitetura: documentos/Documento-de-Arquitetura.md
    - Documentação de Gestão:
        - Termo de Abertura do Projeto: documentos/Termo-de-Abertura-do-Projeto.md
        - Práticas Ágeis: documentos/Práticas-Ágeis-Adotadas.md
        - Monitoramento de issues: documentos/Monitoramento-de-issues-pelo-Zenhub.md

theme: readthedocs
